-- Sccsid:     @(#)dss.ri	2.1.8.1
-- TPCD Benchmark Version 8.0

START TRANSACTION;

--ALTER TABLE REGION DROP PRIMARY KEY;
--ALTER TABLE NATION DROP PRIMARY KEY;
--ALTER TABLE PART DROP PRIMARY KEY;
--ALTER TABLE SUPPLIER DROP PRIMARY KEY;
--ALTER TABLE PARTSUPP DROP PRIMARY KEY;
--ALTER TABLE ORDERS DROP PRIMARY KEY;
--ALTER TABLE LINEITEM DROP PRIMARY KEY;
--ALTER TABLE CUSTOMER DROP PRIMARY KEY;


-- For table REGION
ALTER TABLE REGION SET READ ONLY;

-- For table NATION
ALTER TABLE NATION SET READ ONLY;

-- For table PART
ALTER TABLE PART SET READ ONLY;

-- For table SUPPLIER
ALTER TABLE SUPPLIER SET READ ONLY;

-- For table PARTSUPP
ALTER TABLE PARTSUPP SET READ ONLY;

-- For table CUSTOMER
ALTER TABLE CUSTOMER SET READ ONLY;

-- For table ORDERS
ALTER TABLE ORDERS SET READ ONLY;
create ordered index order_idx on orders(o_totalprice);

-- For table LINEITEM
ALTER TABLE LINEITEM SET READ ONLY;

COMMIT;
