CREATE VIEW REVENUE0 AS
SELECT 
	L_SUPPKEY AS SUPPLIER_NO,
	SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS TOTAL_REVENUE
FROM LINEITEM
WHERE L_SHIPDATE >= DATE '1996-01-01'
AND L_SHIPDATE < DATE '1996-01-01' + INTERVAL '3' MONTH
GROUP BY L_SUPPKEY
